# Generated by Django 3.0.4 on 2020-03-27 23:22s
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import locale
from djmoney.models.fields import MoneyField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100,verbose_name='DA Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('inOff', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=50, verbose_name = 'Station')), #DBS2, DSN1, DEX2
                ('route', models.CharField(max_length = 10)),
                ('logIn', models.DateTimeField(null=True, blank=True)),
                ('logOut', models.DateTimeField(null=True, blank=True)),
                ('mileage', models.IntegerField(verbose_name='Mileage')), #total miles
                ('parcel', models.IntegerField(default=0)),
                ('LWP', models.IntegerField(default=0)),
                ('LVP', models.IntegerField(default=0)),
                ('CRT', models.IntegerField(default=0)),
                ('RL', models.IntegerField(default=0)),
                ('SUP', MoneyField(max_digits=14, decimal_places = 2, default_currency='GBP'))
            ],
        ),
    ]
