# Generated by Django 3.0.4 on 2020-04-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='logOut_time',
            field=models.TimeField(null=True),
        ),
    ]
