# Generated by Django 3.0.4 on 2020-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200721_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vanOwner',
            field=models.BooleanField(default=False),
        ),
    ]
