# Generated by Django 3.0.4 on 2020-04-08 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200408_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='datesList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, null=True, size=None),
        ),
    ]
