# Generated by Django 3.0.4 on 2020-07-23 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_driver_vanowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledamages',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2020, 7, 23), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='creationDate',
            field=models.CharField(default=datetime.date(2020, 7, 23), max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2020, 7, 23), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledamages',
            name='picturesOfIncident',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicledamages',
            name='statmentOfDamage',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='vehiclescheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2020, 7, 23), max_length=50, null=True),
        ),
    ]
