# Generated by Django 3.0.8 on 2020-11-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201129_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclescheduleddate',
            name='registration',
            field=models.CharField(default='DBS2', max_length=20, null=True),
        ),
    ]
